name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-latest]
    name: Building and Test
    steps:
    
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
          sudo apt update
          sudo apt install libgtk-3-dev 
      if: contains(matrix.os, 'ubuntu')
    - name: Build Components
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build doc
      run: cargo doc